### ISSUE TITLE
Set fanart lost when HashDir is true

### ISSUE THREAD

**Issue by Omertron** [YAMJ/yamj-v2#2742]
Original [issue 2745](https://code.google.com/p/moviejukebox/issues/detail?id=2745) created by Omertron on 2014-09-05T17:20:20.000Z:

<b>What steps will reproduce the problem?</b>
1. In properties set mjb.dirHash=true
2. Put a picture file named Set_xxx 1.fanart.jpg
3. Update your library

<b>What is the expected output? What do you see instead?</b>
The fanart picture is well written in the jukebox (inside the hash dir), but in the XML the file isn't &quot;hashed&quot;.

<b>Please use labels and text to provide additional information.</b>

**Comment by pndiku** [comment]
Not sure if this is related, but I've also lost my videoimages since my latest YAMJ update.
