### ISSUE TITLE
Moviemeter plugin doesn't scrape anymore since its API update

### ISSUE THREAD

**Issue by bassie112** [YAMJ/yamj-v2#2759]
Hello,

Since the recent API update of moviemeter, the plugin doesn't scrape the "plot" and "genres" fields anymore. Most likely other fields are affected too.

Can this still be fixed or is the moviemeter plugin not supported anymore?

Tested with latest YAMJ: yamj-2.10-SNAPSHOT-2015-05-03-1557-191eccb-bin

**Comment by Psymania** [comment]
I have noticed this too.

See http://wiki.moviemeter.nl/index.php/API for the new api description (Old Api is deprecated per 1 may 2015)

Client registering via: http://www.moviemeter.nl/site/registerclient/

Please incorporate this new api (if possible), else i would like to have a alternative api to use for dependable dutch scraping info (like movie description).

**Comment by Omertron** [comment]
This was updated to use the new API. Can you give an indication of the errors that you get?

**Comment by bassie112** [comment]
Well, it doesn't give any errors. But it just doesn't put any reference to moviemeter (id or any scraped field) inside the xml files of the scraped movies. So maybe it can't retrieve the id and therefore no fields. Example of scraped movie with latest yamj and only scraping from moviemeter (not imdb or nfo's etc.):



<?xml version="1.0" encoding="UTF-8"?>
<details>
   <movie isExtra="false" isSet="false" isTV="false">
      <id moviedb="tmdb">21755</id>
      <id moviedb="imdb">tt0844286</id>
      <mjbVersion>2.10-SNAPSHOT</mjbVersion>
      <mjbGitSHA>191eccb73560108ad614c0359200e15d3ee91878</mjbGitSHA>
      <xmlGenerationDate>2015-05-13 22:01:14</xmlGenerationDate>
      <baseFilenameBase>The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY</baseFilenameBase>
      <baseFilename>The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY</baseFilename>
      <title source="FILENAME">The Brothers Bloom</title>
      <titleSort>The Brothers Bloom</titleSort>
      <originalTitle source="FILENAME">The Brothers Bloom</originalTitle>
      <year Year="2000-09" source="FILENAME">2008</year>
      <releaseDate source="NFO">2009-05-28</releaseDate>
      <showStatus>UNKNOWN</showStatus>
      <rating>69</rating>
      <ratings>
         <rating moviedb="imdb">69</rating>
         <rating moviedb="NFO">69</rating>
      </ratings>
      <watched>false</watched>
      <watchedNFO>false</watchedNFO>
      <watchedFile>false</watchedFile>
      <top250 source="UNKNOWN">-1</top250>
      <details>The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY.html</details>
      <posterURL>file%3A%2FE%3A%2FVideo%2FFilms%2FLooken%2FFixen%2FEngelse%2520Ondertiteling%2FBrothers%2520Bloom%2C%2520The%2520%282008%29%2Ffolder.jpg</posterURL>
      <posterFile>The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY.jpg</posterFile>
      <fanartURL>UNKNOWN</fanartURL>
      <fanartFile>UNKNOWN</fanartFile>
      <detailPosterFile>The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY.large.png</detailPosterFile>
      <thumbnail>The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY.small.png</thumbnail>
      <bannerURL>UNKNOWN</bannerURL>
      <bannerFile>The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY.banner.jpg</bannerFile>
      <wideBannerFile>The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY.wide.jpg</wideBannerFile>
      <clearLogoURL>UNKNOWN</clearLogoURL>
      <clearLogoFile>UNKNOWN</clearLogoFile>
      <clearArtURL>UNKNOWN</clearArtURL>
      <clearArtFile>UNKNOWN</clearArtFile>
      <tvThumbURL>UNKNOWN</tvThumbURL>
      <tvThumbFile>UNKNOWN</tvThumbFile>
      <seasonThumbURL>UNKNOWN</seasonThumbURL>
      <seasonThumbFile>UNKNOWN</seasonThumbFile>
      <movieDiscURL>UNKNOWN</movieDiscURL>
      <movieDiscFile>UNKNOWN</movieDiscFile>
      <plot source="NFO">Brothers - older Stephen and three years junior Bloom - have been con artists since they were kids. Stephen is the mastermind, for who the intricacy of the story used in the con is as important as the positive outcome of the swindle. Bloom is the main character of Stephen's stories, the character he considers the anti-hero. As adults, they travel the world and never enlist the same people twice in their cons, except for their consistent sidekick, the mysterious and primarily silent Bang Bang, a Japanese woman who just appeared in their lives one day and who has a penchant for blowing things up. As Bloom hits his mid-thirties, he wants to quit the business as he is losing his own identity to that of the characters he portrays; he doesn't know anymore what is real and what is make-believe. Stephen talks him into one last con, the mark to be the eccentric, lonely but beautiful New Jersey heiress, Penelope Stamp. Penelope's primary past-time in life is to, as she calls it, 'borrow hobbies': when she sees something she likes, she learns how to do it solely through reading books. As the brothers go through their final con on Penelope, three main problems may occur to thwart the plan. First, the brothers' former mentor and now arch enemy, Diamond Dog, may exact his long awaited revenge on the brothers. Second, Penelope may end up being more unpredictable than all their former marks. And third, Bloom, who has let love slip by in his life, may fall for Penelope. But through the process, no one ever really knows who is conning who.</plot>
      <outline source="NFO">Brothers - older Stephen and three years junior Bloom - have been con artists since they were kids. Stephen is the mastermind, for who the intricacy of the story used in the con is as important as the...</outline>
      <quote source="UNKNOWN">UNKNOWN</quote>
      <tagline source="IMDB">They'd never let the truth come between them</tagline>
      <country index="Country_USA_1" source="NFO">USA</country>
      <company source="IMDB">Endgame Entertainment</company>
      <runtime source="MEDIAINFO">1h 53m</runtime>
      <certification source="IMDB">PG-13</certification>
      <season>-1</season>
      <language source="MEDIAINFO">English</language>
      <subtitles>YES</subtitles>
      <trailerExchange>NO</trailerExchange>
      <trailerLastScan>UNKNOWN</trailerLastScan>
      <container source="MEDIAINFO">MPEG-4</container>
      <videoCodec>AVC</videoCodec>
      <audioCodec>AAC LC (en)</audioCodec>
      <codecs>
         <audio count="1">
            <codec bitrate="91"
                   channels="2"
                   codecId="40"
                   codecIdHint="UNKNOWN"
                   format="AAC"
                   formatProfile="LC"
                   formatVersion="UNKNOWN"
                   language="en"
                   langugageFull="English"
                   source="MEDIAINFO">AAC LC</codec>
         </audio>
         <video count="1">
            <codec bitrate="827"
                   codecId="avc1"
                   codecIdHint="UNKNOWN"
                   format="AVC"
                   formatProfile="High@L4"
                   formatVersion="UNKNOWN"
                   source="MEDIAINFO">AVC</codec>
         </video>
      </codecs>
      <audioChannels>2</audioChannels>
      <resolution source="MEDIAINFO">1280x528</resolution>
      <videoSource source="UNKNOWN">UNKNOWN</videoSource>
      <videoOutput source="MEDIAINFO">720p 24Hz</videoOutput>
      <aspect source="MEDIAINFO">2.400:1</aspect>
      <fps source="MEDIAINFO">23.976</fps>
      <fileDate>2015-05-12</fileDate>
      <fileSize>750 MB</fileSize>
      <first>100.Bloody.Acres.2012.720p.BluRay.x264.YIFY</first>
      <previous>Bonded%20by%20Blood%202%20%282015%29</previous>
      <next>The%20Captive%20%282014%29</next>
      <last>You.Can%27t.Kill.Stephen.King.2012.720p.BluRay.x264.YIFY</last>
      <libraryDescription>TEST</libraryDescription>
      <prebuf>-1</prebuf>
      <genres count="1" source="NFO">
         <genre index="Genres_Avontuur_1">Avontuur</genre>
      </genres>
      <director>Rian Johnson</director>
      <directors count="1" source="NFO">
         <director>Rian Johnson</director>
      </directors>
      <writers count="1" source="IMDB">
         <writer>Rian Johnson</writer>
      </writers>
      <cast count="25" source="IMDB">
         <actor>Rachel Weisz</actor>
         <actor index="Cast_Adrien%20Brody_1">Adrien Brody</actor>
         <actor>Mark Ruffalo</actor>
         <actor>Rinko Kikuchi</actor>
         <actor>Robbie Coltrane</actor>
         <actor>Maximilian Schell</actor>
         <actor>Ricky Jay</actor>
         <actor>Zachary Gordon</actor>
         <actor>Max Records</actor>
         <actor>Andy Nyman</actor>
         <actor>Noah Segan</actor>
         <actor>Nora Zehetner</actor>
         <actor>Ram Bergman</actor>
         <actor>Craig Johnson</actor>
         <actor>Dubravko Jovanovic</actor>
         <actor>Esme Tyler</actor>
         <actor>Jovan Vitas</actor>
         <actor>Ana Sofrenovic</actor>
         <actor>Vladimír Kulhavý</actor>
         <actor>Alek Rodic</actor>
         <actor>Josif Tatic</actor>
         <actor>Slobodan Custic</actor>
         <actor>Branka Pujic</actor>
         <actor>George Bocchetti</actor>
         <actor>Ellis Derham</actor>
      </cast>
      <awards count="3">
         <event count="1" name="Chlotrudis Awards">
            <award name="Chlotrudis Award"
                   nominated="1"
                   nominations="Best Supporting Actress"
                   won="0"
                   year="2010">Chlotrudis Award</award>
         </event>
         <event count="1" name="Satellite Awards">
            <award name="Satellite Award"
                   nominated="1"
                   nominations="Best Actor in a Motion Picture, Comedy or Musical"
                   won="0"
                   year="2008">Satellite Award</award>
         </event>
         <event count="1" name="Stockholm Film Festival">
            <award name="Bronze Horse"
                   nominated="1"
                   nominations="Bronze Horse"
                   won="0"
                   year="2008">Bronze Horse</award>
         </event>
      </awards>
      <business budget="$20,000,000">
         <gross country="USA">$3,519,627</gross>
         <gross country="UK">£36,861</gross>
         <openweek country="USA">$90,400</openweek>
         <openweek country="UK">£36,861</openweek>
      </business>
      <didyouknow count="15">
         <trivia>Rachel Weisz learned how to play piano, violin, accordion, and break-dance, to juggle, do karate, play Ping-Pong, banjo, unicycle, and even skateboard for her role as Penelope.</trivia>
         <trivia>The card trick performed by Rachel Weisz took her a month to learn, practicing every day. The shot itself took 11 takes.</trivia>
         <trivia>Rian Johnson originally had Mark Ruffalo in mind to play the part that Adrien Brody eventually played. It was the two actors themselves that suggested swapping.</trivia>
         <trivia>The three main characters are based on characters from James Joyce's "Ulysses" (which in turn is based on Homer's "Odyssey"). Stephen is based on Stephen Daedalus, a restless young writer in two of Joyce's novels; in "The Brothers Bloom", Stephen plans their cons with a writer's flair. Bloom is based on Leopold Bloom, who is wandering around Dublin, trying to find himself and his way back to his wife. In The Brothers Bloom, Bloom is figuratively looking for himself, and ultimately finds his way to Penelope. In "The Odyssey", Penelope is Odysseus' wife who waits for him through all of his travels; likewise, here, Penelope awaits Bloom through his wanderings.</trivia>
         <trivia>Adrien Brody helped Rachel Weisz learn how to skateboard and to rap.</trivia>
         <trivia>Penelope's house in New Jersey is actually the Peles castle located in Sinaia, Romania.Also, the building near the sea, where Bloom is going to meet the kidnappers, is the Casino of Constanta, Romania.</trivia>
         <trivia>Penelope's quote, "A picture is a secret about a secret. The more it tells, the less you know" is actually a quote by acclaimed American photographer Diane Arbus (1923-1971). The biographical film Fur: An Imaginary Portrait of Diane Arbus (2006), featured Nicole Kidman as Arbus, one of the 20th century's most revered photographers. Incidentally, "arbus" is Russian for "water melon", which might explain why one gets turned into a camera by the Penelope character.</trivia>
         <trivia>Rachel Weisz was the first actor to sign on to the film.</trivia>
         <trivia>Rian Johnson lists The Sting (1973) and Dirty Rotten Scoundrels (1988) as key inspirations for the film. More unconventionally, the legendary concert film The Last Waltz (1978) also influenced his writing process, to the point that The Brothers Bloom contains a multitude of references to The Band. During initial discussions with Mark Ruffalo, Johnson clarified that he wanted to capture a particular '70s folk rock vibe, envisioning Stephen as Robbie Robertson.</trivia>
         <trivia>Early in the film a character says, "The man named Charleston you met nine months and a thousand years ago at the hotel bar in Jodhpur is dead." to which Stephen later says "That's Kipling, isn't it? He stole that from Kipling." This is in reference to Rudyard Kipling's "The Man who Would Be King". In the film adaptation (The Man Who Would Be King (1975)), there is a line spoken by Michael Caine, saying he is "The same and not the same - who sat beside you in the first class carriage on the train to Marwar Junction; three summers and a thousand years ago...", but the line does not appear in the original short story.</trivia>
         <trivia>Rian Johnson always intended Rinko Kikuchi's role as Bang Bang to be silent.</trivia>
         <trivia>Bang Bang says only three words in the entire film, not counting the karaoke she does.</trivia>
         <trivia>Tom Cruise is credited with special thanks in regards to the film due to his initial interest in the film that led to a lengthy 3 hour meeting with Rian Johnson. Cruise's analysis of the script led to a few significant changes of the key elements of the script. As this meeting occurred precisely the same day Cruise's company was taken off by Paramount, Rian felt this was a more than generous act on Cruise's behalf. However, due to scheduling conflicts as well as other factors, Cruise could never be a serious consideration for one of the lead roles.</trivia>
         <trivia>Ricky Jay, the narrator, is an actor who has appeared in films for such filmmakers as Paul Thomas Anderson and David Mamet, but he is perhaps better known as an expert on the histories of magic, "spirit" photography, and con artistry, and as such is a logical choice to narrate a film about con artists. Rian Johnson had originally asked Jay to play The Curator, but Jay's schedule didn't allow for that, so Johnson hired Robbie Coltrane for that role instead.</trivia>
         <trivia>The script's original title was "Penelope", after Rachel Weisz's character.</trivia>
      </didyouknow>
      <indexes>
         <index encoded="All" originalName="All" type="All">All</index>
         <index encoded="Rating" originalName="Rating" type="Rating">Rating</index>
         <index encoded="Rian Johnson" originalName="Director" type="Director">Rian Johnson</index>
         <index encoded="B" originalName="Title" type="Title">B</index>
         <index encoded="PG-13" originalName="Certification" type="Certification">PG-13</index>
         <index encoded="New-Movies" originalName="New-Movie" type="New-Movie">New-Movies</index>
         <index encoded="2000-09" originalName="Year" type="Year">2000-09</index>
         <index encoded="Stockholm Film Festival" originalName="Award" type="Award">Stockholm Film Festival</index>
         <index encoded="Ellis Derham" originalName="Actor" type="Actor">Ellis Derham</index>
         <index encoded="USA" originalName="Country" type="Country">USA</index>
         <index encoded="Avontuur" originalName="Genres" type="Genres">Avontuur</index>
         <index encoded="Movies" originalName="Movies" type="Movies">Movies</index>
         <index encoded="TEST" originalName="Library" type="Library">TEST</index>
         <index encoded="HD" originalName="HD" type="HD">HD</index>
         <index encoded="Rian Johnson" originalName="Writer" type="Writer">Rian Johnson</index>
      </indexes>
      <files>
         <file firstPart="1"
               lastPart="1"
               season="-1"
               size="786717358"
               subtitlesExchange="NO"
               title="UNKNOWN"
               vod=""
               watched="false">
            <fileLocation>E:\Video\Films\Looken\Fixen\Engelse Ondertiteling\Brothers Bloom, The (2008)\The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY.mp4</fileLocation>
            <fileURL>file:///opt/sybhttpd/localhost.drives/SATA_DISK/Video/Films/Looken/Fixen/Engelse%20Ondertiteling/Brothers%20Bloom%2C%20The%20%282008%29/The.Brothers.Bloom.2008.720p.BrRip.x264.YIFY.mp4</fileURL>
            <fileTitle part="1" source="UNKNOWN">UNKNOWN</fileTitle>
         </file>
      </files>
   </movie>
</details>

**Comment by chocoprinsje** [comment]
ok i have downloaded the new api  but how can i used it ?
or is it already in yamj-2.10-SNAPSHOT-2015-05-27-1508-7ffe331-bin version?

**Comment by Omertron** [comment]
The API is included in YAMJ already, it should have been a seamless change over.

So, download the latest YAMJ, and try re-scanning with that version

**Comment by chocoprinsje** [comment]
thank you thats the trick
