### ISSUE TITLE
Error: Could not find or load main class com.moviejukebox.MovieJukebox

### ISSUE THREAD

**Issue by dolfin00** [YAMJ/yamj-v2#2761]
I am getting this error when running My_YAMJ.cmd file created by YAMJ GUI Config:  Could not find or load main class com.moviejukebox.MovieJukebox.  I just downloaded and installed yamj-v2-2.9. I have only created the cmd and library files from GUI config and copied moviejukebox.properties file into the yamj-v2-2.9\distribution\conf directory.

I uninstalled old versions of Java and installed 1.8_45.

Any suggestions?

Thank you!!

**Comment by Omertron** [comment]
This usually means that you've not installed correctly.

Check that your lib folder is correct by unpacking the folder from the latest zip file http://mediaplayersite.com/yamj_latest

Have you changed the paths to anything else?

**Comment by modmax** [comment]
Tried latest release and no problemns with teh default installation when lib-folder was cleared.
