### ISSUE TITLE
Top 250 from IMDB not extracting

### ISSUE THREAD

**Issue by dd314159** [YAMJ/yamj-v2#2762]
I noted my Top 250 category was a mess so in an attempt to clean this up, I downloaded the latest
Snapshot, deleted the LIB folder and extracted the zip file.
yamj-2.10-SNAPSHOT-2015-05-27-1508-7ffe331
Just ran an update with that snapshot and 
Star Wars: Episode IV - A New Hope (1977)
using an .nfo file with one line...http://www.imdb.com/title/tt0076759 
xml output had this as #1 rather than #19 in IMDB top 250
<top250 source="IMDB">1</top250>
Although the other 2 StarWars in the top 250 Return of the Jedi #74 & The Empire Strikes Back #12
Pulled the correct numbers?
I am using exploded sets property for Top 250

**Comment by modmax** [comment]
The Tag for Top 250 was formerly "Top 250", now it's called "Top Rated Movies"
