### ISSUE TITLE
Oct 28 build destroyed all art

### ISSUE THREAD

**Issue by wryker** [YAMJ/yamj-v2#2766]
Go here http://www.networkedmediatank.com/showthread.php?tid=72880&pid=666495#pid666495 for details - very upset that everything is 'gone' and continues to error error error

**Comment by Omertron** [comment]
Please revert to this version http://mediaplayersite.com/sites/default/files/YAMJ/yamj-2.10-SNAPSHOT-2015-08-21-1902-f92030f-bin.zip

That should fix most of the issues you are having.

**Comment by malsec** [comment]
Thanks Omertron :-) Had errors with posters not downloading. Version 2015-08-21 fixed my issues.

**Comment by Omertron** [comment]
Modmax and I have discussed what needs to be done to update the builds, so
we will be doing that over the next few days.

Just make sure you keep hold of this build to roll back to if required.

**Comment by modmax** [comment]
Fixed with #2767
