### ISSUE TITLE
Latest build generates an empty index.htm

### ISSUE THREAD

**Issue by ojsotto** [YAMJ/yamj-v2#2768]
2015-11-05-1109-f53b88c-bin.zip
Had to get back to yamj-2.10-SNAPSHOT-2015-05-27-1508-7ffe331-bin to m

**Comment by hispanico957** [comment]
Yes also me i try different previous version but the yamj-2.10-SNAPSHOT-2015-05-27-1508-7ffe331-bin its the only good that build index correctly

Hispa

**Comment by modmax** [comment]
This has been fixed at least with the latest version from the mediaplayersite
