### ISSUE TITLE
Wrong text code page

### ISSUE THREAD

**Issue by swasher** [YAMJ/yamj-v2#2769]
I'm using old build, and all fine. Today I try install latest yamj-2.10-SNAPSHOT-2016-01-16-0120-1c8673a-bin.zip and got such result:
![image](https://cloud.githubusercontent.com/assets/1525918/12377195/220fa576-bd1d-11e5-82d8-2707e68e3cb0.png)

When I return my old `lib` directory back (build about summer 2015), all was well again.
p.s I'm use kinopoink source for scraping.

**Comment by krial** [comment]
I have the same probt\lem too.

**Comment by Omertron** [comment]
I *think* I have found the issue, the pages are requested in the default character set (UTF-8).

I will make the changes to get them in the correct format

**Comment by krial** [comment]
Just tried the new version.
At first sight, everything is OK

Thanks a lot.

**Comment by Omertron** [comment]
Excellent, thanks for testing
