### ISSUE TITLE
Invalid runtime in xml file

### ISSUE THREAD

**Issue by danielpaten** [YAMJ/yamj-v2#2770]
Hello,
I try the last build and the problem persists
(yamj-2.10-SNAPSHOT-2016-01-16-0120-1c8673a-bin)

The runtime information for some films is wrong in the generated xml file.
For example yamj generate :
&lt;runtime source="MEDIAINFO"&gt;131h 42m&lt;/runtime&gt; :-)
And mediainfo give me :
Duration                                 : 2h 11mn
It seems that the problem appears when time is > 2 hours (but I'm not sure of that)

**Comment by danielpaten** [comment]
Perhaps an idea to follow...
For all the films with incorrect runtime, mediainfo display the duration with a real number with 6 zero after a dot.
Duration                                 : 4054466.000000 <== the problem ?
Duration                                 : 1h 7mn
Duration                                 : 1h 7mn 34s 466ms

And for other films 
Duration                                 : 5405275
Duration                                 : 1h 30mn
Duration                                 : 1h 30mn 5s 275ms
Duration                                 : 1h 30mn

**Comment by modmax** [comment]
Hi daniel,
your assumption is correct. If a . is contained within the runtime string, then this is not
correctly parsed.

I will fix this problem as soon as possible.
