### ISSUE TITLE
Too long first scan

### ISSUE THREAD

**Issue by dima-vy** [YAMJ/yamj-v2#2772]
I have library with 95 titles. As usual i have a script which deletes a Jukebox directory and rescanning the library. With yamj 2.9 it was taking couple of hours, but with latest yamj 2.10 it took 17 hours. This is the log file. May be anybody can point me where is a problem?
Thank you
[moviejukebox.log.copy.19.02.2016.txt](https://github.com/YAMJ/yamj-v2/files/138614/moviejukebox.log.copy.19.02.2016.txt)

**Comment by Omertron** [comment]
When it is searching for posters, there is a significant pause (~1 hour).

I presume that you are getting slowed down, probably by the site.

A larger question is why you keep deleting the jukebox?

**Comment by dima-vy** [comment]
Thanx for your answer! The reason is following - i don't wan't to keep jukebox files for the movies i've deleted. And the second reason - after deleting the movie, it's still listed under the "New" category. May be it is the skin issue?

Is there any way to avoid being slowed by the site? Is there anyone else who has such issues?

Thank you

**Comment by Omertron** [comment]
YAMJ will delete the files that are no longer in use, so when you delete the movie, the jukebox files will be removed too.

You can use `mjb.forceIndexOverwrite=true` to recreate the indexes, or you can just delete the XML files for the new indexes to force them to be re-created.

As to speeding up the jukebox, you can store the artwork with the movie and then it does not need to be downloaded each time.

**Comment by dima-vy** [comment]
For some reason YAMJ doesn't delete jukebox files of the deleted content. May be i'm missing something? Is there anything to define for deleting unused files?

**Comment by Omertron** [comment]
You can either add `-c` to the command line, or you can use the property `mjb.jukeboxClean=true` to your properties file.

**Comment by dima-vy** [comment]
Thank you:)
Finally it works fine. Somehow i missed this property:(
Thank you again for your help

**Comment by Omertron** [comment]
The wiki is not very well organised, but if you search for "command" you can see all the command line options and "properties" for all the property settings

**Comment by dima-vy** [comment]
Hi!
I didn't find any other way to contact you, so i'll try here. I've added one movie, and the scan also took almost one hour. I'm attaching the log file here. May be you can see which site slowing me down? Looks like the longest delay happens when the search using google. I didn't altered any property regarding the search... The movie i've added is http://www.imdb.com/title/tt4466864. You can see it in log arround 18:58:25, and then continue around 18:58:35, and then 19:41:58
[moviejukebox.log.23.02.2016.txt](https://github.com/YAMJ/yamj-v2/files/143316/moviejukebox.log.23.02.2016.txt)

Thank you very much for your help

Dima

**Comment by Omertron** [comment]
It looks like impawards is being really slow for you. I would remove that from the poster.search.priority property and see what happens.

Unless you have a really slow machine, I would increase your threading settings. On my slow Atom based NAS I use `mjb.MaxThreadsDownload=4` & `mjb.MaxThreadsProcess=2`. I would suggest using those as well. If you have a faster processor, then you can change them to 4 & 4 or even 8 & 8.

**Comment by dima-vy** [comment]
Thanx for the advices!! I'm running yamj on QNAP NAS TS-212, it has one core ARM processor and 256MB of RAM. Usual scanning on this device takes about minute and a half

**Comment by dima-vy** [comment]
I tried to remove impawards, and it didn't help. I tried to left just yahoo, and it also didn't help. Right now i returned everything back. Can you look at the following part of log:
`[08:37:54 - Thread-1] MovieJukebox$3: Processing new video: Formula lubvi
[08:37:54 - Thread-1] MovieJukebox: Jukebox XML file not found: /share/MD0_DATA/HD_rus/Jukebox/Formula.lubvi.1984.BDRip.1080p.x264.HDReactor.xml
[08:37:54 - Thread-1] MovieJukebox: Scanning for information on Formula.lubvi.1984.BDRip.1080p.x264.HDReactor
[08:37:55 - Thread-1] FileTools: No matching files [jpg, jpeg, gif, bmp, png, tbn] found for /Formula.lubvi.1984.BDRip.1080p.x264.HDReactor
[08:37:55 - Thread-1] PosterScanner: No local poster found for Formula.lubvi.1984.BDRip.1080p.x264.HDReactor
[08:37:55 - Thread-1] ImdbInfo: Querying IMDB for http://www.imdb.com/find?q=Formula+lubvi+(1984)&s=tt&ttype=ft&site=aka
[08:37:56 - Thread-1] ImdbInfo: querying Google for Formula lubvi
[08:37:56 - Thread-1] ImdbInfo: Google search: http://www.google.com/search?q=Formula+lubvi+(1984)+site%3Awww.imdb.com&meta=
[09:14:03 - Thread-1] PosterScanner: Searching online for Formula.lubvi.1984.BDRip.1080p.x264.HDReactor
[09:14:03 - Thread-1] PosterScanner: Using imdb to search for a Movie poster for Formula lyubvi (TV Movie 1984)
[09:14:04 - Thread-1] PosterScanner: Using impawards to search for a Movie poster for Formula lyubvi (TV Movie 1984)`
There is a long period between:
[08:37:56 - Thread-1] ImdbInfo: querying Google for Formula lubvi
[08:37:56 - Thread-1] ImdbInfo: Google search: http://www.google.com/search?q=Formula+lubvi+(1984)+site%3Awww.imdb.com&meta=

and next line:
[09:14:03 - Thread-1] PosterScanner: Searching online for Formula.lubvi.1984.BDRip.1080p.x264.HDReactor
May be it's some problem with ImdbInfo?

Thank you

**Comment by Omertron** [comment]
I presume that you don't use any nfo files? So this is YAMJ searching imdb via google for the IMDB id (tt0216755)

Usually, this would take <1 second, but for whatever reason, I think you are getting blocked on google. or slowed down.

There are a couple of things you can do. Firstly, you can create a NFO file for each movie, this will speed up the look up of each movie. The simplest NFO file just uses the IMDB url in a file named the same as the movie with `.nfo` at the end:

`www.imdb.com/title/tt0216755/
`

**Comment by dima-vy** [comment]
The interesting thing, that i'm not slowing down on all movies, just on some. The other thing - YAMJ 2.9 is getting info for this movie in a second also
You are right, i'm not using nfo files. I've added the nfo for this movie (attached, just with nfo instead of txt)) but i got error:
MovieNFOReader: Failed to find any information in Formula.lubvi.1984.BDRip.1080p.x264.HDReactor.nfo
[Formula.lubvi.1984.BDRip.1080p.x264.HDReactor.txt](https://github.com/YAMJ/yamj-v2/files/146350/Formula.lubvi.1984.BDRip.1080p.x264.HDReactor.txt)

P.S. I hope my questions don't make you too much trouble :)

**Comment by dima-vy** [comment]
Hi!
I tried the following: i created a new directory, set up the latest version of yamj, with default parameters. I copied on file the directory The.Physician.2013.BDRip.1080p-MediaClub.mkv, and run YAMJ

**Comment by Omertron** [comment]
I will try and have a look at this sometime this week.

**Comment by dima-vy** [comment]
Thank you!!!

**Comment by dotternetta** [comment]
Hi, I know this is old news, but I searched all of Google, yes really, and this is the only thread I found which describes exactly my problem. Did you solve it? Please let me know. 1 new movie takes 2 hours. And I tried everything, but nothing helps.

**Comment by dima-vy** [comment]
Hi!
No, I didn't solve it
