### ISSUE TITLE
Box Set Page Won't Open

### ISSUE THREAD

**Issue by Kickarz** [YAMJ/yamj-v2#2773]
Hello,
I followed the NFO file method outlined in the wiki to group my movies into a sets
EG:
```
  <sets>
    <set>Alien Collection</set>
  </sets>
```
However when YAMJ compiles the jukebox menus, it replaces any space characters in the set name with a **%20** when defining the `var xon=` in all menu html. This returns an error when select a box set with my PCH-C200.

So instead of...
```
var xon= [
   "A Million Ways to Die in the West","A Time to Kill","A-Team","Set_Alien Collection_1","...etc..."];
```
I get...
```
var xon= [
   "A Million Ways to Die in the West","A Time to Kill","A-Team","Set_Alien%20Collection_1","...etc..."];
```
Manually editing each index html to remove the %20 the saving will fix these menu pages but only until I update the menus (which is quite often).

Does anyone have any thoughts on why I might try to resolve this?

Thanks so much!

**Comment by Omertron** [comment]
Can you try adding this line to the top of your NFO file
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`

Also, make sure the file is saved in UTF-8 format (using notepad++)

**Comment by Kickarz** [comment]
Hi Omertron,

I did as you suggested and YAMJ is still replacing the space characters with a %20.
Every individual (not part of a set) movie name keeps their space characters intact, it just seems to be the box set names which are affected.

Really appreciate any other suggestions?

**Comment by Omertron** [comment]
I don't recognise the tag, can you post the rest of the xml?

**Comment by Kickarz** [comment]
Hi Omertron,
As it turns out the problem was cause by me as I attempted to modify Excal's Redefined skin. I have now gone back to using the unadulterated skin and everything is working as it should.
I guess if it's not broken - don't fix it!
Thank you again for your suggestions and patience, I'll do my best to leave well enough alone.
Cheers.

**Comment by Omertron** [comment]
It's always worth a try to modify something to your liking. Keep trying, you probably just did a small error, as long as you are able to roll back, it will be fine :)
