### ISSUE TITLE
Too long scan with GTSpecial skin and Zappiti skin after fix of 2772

### ISSUE THREAD

**Issue by dima-vy** [YAMJ/yamj-v2#2775]
After fixing issue 2772 (https://github.com/YAMJ/yamj-v2/commit/b08db88), when running YAMJ with skins GTSpecial and Zappiti, it also take more than hour for the directory with 2 movies.
log file attached
[moviejukebox.log.GTSpecial.txt](https://github.com/YAMJ/yamj-v2/files/160001/moviejukebox.log.GTSpecial.txt)
Looks like the problem is line:
[18:38:25 - Thread-6] MovieJukebox$7: Writing detail HTML to movie: Formula.lubvi.1984.BDRip.1080p.x264.HDReactor

**Comment by Omertron** [comment]
Please try the latest version, I've rolled back some changes that might have caused the issue.

**Comment by dima-vy** [comment]
Checked, works fine :+1:

**Comment by Omertron** [comment]
thanks for testing it
