### ISSUE TITLE
Fanart not beeing downloaded with moviemeter plugin

### ISSUE THREAD

**Issue by pbosgraaf** [YAMJ/yamj-v2#2778]
Hi,

Running 2.10  Revision SHA: 60e15b1b5346c1ae43df295df65d7210a86bed26 (Custom Build)

I enabled the moviemeter plugin in moviejukebox.properties.
mjb.internet.plugin=com.moviejukebox.plugin.MovieMeterPlugin

For none of my movies the fanart is beeing downloaded.

Logs:

[11:23:37 - Thread-2] FanartScanner: No local Fanart found for XX attempting to download
[11:23:37 - Thread-2] ArtworkScanner: XX movieart not required
[11:23:37 - Thread-2] ArtworkScanner: XX moviedisc not required
[11:23:37 - Thread-2] ArtworkScanner: XX movielogo not required
[11:23:37 - Thread-2] MovieJukebox$3: Finished: XX (20/95)

Somehow the fanart files are not downloaded to the filesystem, and also not in the XML:

      <fanartURL>UNKNOWN</fanartURL>
      <fanartFile>UNKNOWN</fanartFile>

Could this be a bug or am i doing something wrong?

**Comment by Omertron** [comment]
MovieMeter does not download fanart, that is usually from TheMovieDb

Does the movie have fanart on themoviedb.org ?

**Comment by pbosgraaf** [comment]
Hi,

Thanks for the quick reply!
Yes it does have fanart on themoviedb.org.
The fanart downloads correct with my old yamj-2.9 installation. (I tried re-generating the jukebox with the backup of my old install)

I'll try to enable imdb in yamj-2.10 to see if that makes a difference.

What configuration parameter tells yamj to download the fanart in the first place? I can't seem to find it anywhere in the configuration files.

**Comment by Omertron** [comment]
Can you give me your properties file (moviejukebox,properties) plus a couple of example filenames where it doesn't get the fanart?

**Comment by pbosgraaf** [comment]
Sure, no problem.
I switched to imdb to have a good comparison against my old 2.9 install. (that uses imdb)
You can see the differences in the 2.9 and 2.10 XML files.
Both installs are using the same moviejukebox.properties file.



[Concussion.2015.720p.BluRay.DD5.1.DTS.x264.NLSubs-QoQ.xml-2.9.txt](https://github.com/YAMJ/yamj-v2/files/171694/Concussion.2015.720p.BluRay.DD5.1.DTS.x264.NLSubs-QoQ.xml-2.9.txt)
[Concussion.2015.720p.BluRay.DD5.1.DTS.x264.NLSubs-QoQ.xml-2.10.txt](https://github.com/YAMJ/yamj-v2/files/171695/Concussion.2015.720p.BluRay.DD5.1.DTS.x264.NLSubs-QoQ.xml-2.10.txt)
[moviejukebox.properties.txt](https://github.com/YAMJ/yamj-v2/files/171696/moviejukebox.properties.txt)

**Comment by pbosgraaf** [comment]
Confirmed, thanks!
