### ISSUE TITLE
Installation/classpath issue

### ISSUE THREAD

**Issue by shaimo** [YAMJ/yamj-v2#2785]
Apologies if this is a stupid question but I don't know enough about Java. I had this working for a long time on my computer but it stopped downloading movie plots, etc so I figure I will re-install the newest version. Last time I got the code from Google. It seems that now that the code is hosted on github the file structure is very different and the installation guide doesn't work with it out of the box. I found the MovieJukebox.bat file buried in the distribution\conf folder but when I try to run it I get:
```
Error: Could not find or load main class com.moviejukebox.MovieJukebox
```

MoviesJukebox.bat does have the switch:
```
 -classpath .;resources;lib/*
```

What am I missing?
Thanks!

**Comment by shaimo** [comment]
I found out I need to use Maven to actually compile and install everything. I guess the Google code repository contained the actual jar, etc after this process. This should be documented somewhere...

**Comment by modmax** [comment]
You can download all packages from Omertrons mediaplayer site, so that you do not need maven to compile and install everything.

http://www.mediaplayersite.com/YAMJ_Latest

Github is just the source repository.

**Comment by shaimo** [comment]
Note that all the installation guides out there (including the wiki one)
point to the Google code site which gets redirected to the Github repo.
None of them has that link above...

**Comment by modmax** [comment]
I added a link to the mediaplayer site on the readme page.
