### ISSUE TITLE
File name from pictures and xml files are bad.

### ISSUE THREAD

**Issue by danielpaten** [YAMJ/yamj-v2#2789]
Hello,
I install the last build yamj-2.10-SNAPSHOT-2016-10-04-0917-87b0f8a
Now, some file name from pictures and xml files are not correct.
Sample:
Original filename : Les Schtroumpfs 06 - La flûte à six Schtroumpfs (1990) Fr DVDRip.mkv
Picture filename : Les Schtroumpfs 06 - La flûte a six Schtroumpfs (1990) Fr DVDRip.jpg
You see the "accent" over the "a" is missing ... 
With version -2.10-2016-01-20-1903-2c4c75d the filename for the picture and xml are correct

Daniel

**Comment by Omertron** [comment]
The filenames are usually stripped of their accents to avoid issues with file systems.

Are the XML filenames the same as the jpg filename?

**Comment by danielpaten** [comment]
OK, I understand the goal.
But then all my images will end up duplicate? And YAMJ no longer finds my images already existing.
And only the accent of "a" is deleted that of the "flûte" has remained, so this is not going to help on some file system.
One suggestion is to configure this “stripped” as yes or no in the moviejukebox.properties file.

Thank you for the wonderful work on YAMJ
D

**Comment by Omertron** [comment]
Yes, there is a property that controls what characters are changed and what they are changed to.

**Comment by danielpaten** [comment]
Of course ... Sorry .... shame on me
There is actually an new value added for the property: mjb.charset.filename.translate in the file moviejukebox-default.properties ... (\ u00e0-a)
Sorry for not seeing it ...
Thanks again …
D.

**Comment by Omertron** [comment]
It's ok, I was just looking for it :+1:  Can't find it myself!

Now, you do need to be careful of that property, but please try it and see that it works for you

**Comment by danielpaten** [comment]
Ok It's working perfect ...
I copy the mjb.charset.filename.translate property in my moviejukebox.properties.
Then I do the update to the last version of Yamj ... And It works perfectly
Thanks again

**Comment by Omertron** [comment]
Excellent, thanks for letting me know
