### ISSUE TITLE
YAMJ/Eversion causes PCH to crash due to plot size

### ISSUE THREAD

**Issue by Tyrindor** [YAMJ/yamj-v2#2791]
http://www.networkedmediatank.com/showthread.php?tid=74038

I discussed this here with Omertron, if you have multiple large episode shows on the same page, it results in the "Other_TV_Show_X.xml" files getting too large, crashing the PCH. For example, multiple 300+ episode anime series.

The best way to handle this would probably be a setting that allows you to not index episode plots for series over the set amount. Example: MaxPlotsToIndex=300 would index the the episode plots of any shows with 300 or less episodes, but ignore episode plots for any shows with more than that.

This is nothing more than a bandaid fix, but I can't think of any other solution until we have PCHs with more than 1GB of RAM.

**Comment by Tyrindor** [comment]
Doesn't really seem to be any development on v2 anymore. This is pretty much a dead breaker for me at this point, running no episode plots is annoying and I get a crash every other day if I don't.

**Comment by Omertron** [comment]
Apologies, completly forgot about this issue. I will look at it tomorrow and sort out a quick fix for it.

**Comment by Omertron** [comment]
Use the property `mjb.episodePlotSize` to set the maximum size for the plot used in TV episodes.

**Comment by Tyrindor** [comment]
Thanks very much, doing a fresh jukebox rebuild and I will report back if I have any issues with it. 👍
