### ISSUE TITLE
Not Rated certification returned for all movies since 18/08/2017

### ISSUE THREAD

**Issue by ajs6000** [YAMJ/yamj-v2#2795]
Im running the latest dev build (yamj-2.10-SNAPSHOT-2017-07-23-1849-9413e51-bin.zip) and since around 18/08/2017 all my new scans return "Not Rated" for new movies. TV series are still working fine.

**Comment by Omertron** [comment]
What plugin are you using for Movies?

**Comment by ajs6000** [comment]
I'm using ImdbPlugin, which I think is the default.

**Comment by Omertron** [comment]
Unless you really need data from IMDB, I would suggest that you change to themoviedb plugin as that uses an API that is far more stable than the IMDB page scraping.
