### ISSUE TITLE
posterscanner failing on some tvdb jpgs

### ISSUE THREAD

**Issue by doubledrat** [YAMJ/yamj-v2#2796]
e.g.
PosterScanner: getUrlDimensions error: Not a JPEG file: starts with 0xff 0xd9: can't open url: http://thetvdb.com/banners/seasons/315068-2-3.jpg

I currently have 11 of these failures in my log.

I've downloaded the above file and it does not start with ff d9, it starts with ff d8

**Comment by methilnet** [comment]
put poster.scanner.Validate=false in your moviejukebox.properties file.
look like something is wrong or has changed at the tvdb once more ...

**Comment by JasperZ28** [comment]
Hi,
Yes same issue this end, had guessed TVDB had changed something.
Please advise of any updates please.
Thank you, 
BTW Love YAMJ !!

**Comment by Omertron** [comment]
`poster.scanner.Validate=false` will solve the issue with the posters.

This setting was really designed for websites with lax aspect ratios, so shouldn't affect theTVDB images.

A couple of runs of YAMJ should fix the issues. If there is the same issue with banners, then `banner.scanner.Validate=false` will work too,
