### ISSUE TITLE
Error getting covers from TheTVDB

### ISSUE THREAD

**Issue by Verakso** [YAMJ/yamj-v2#2797]
I can't quite figure out if TheTVDB has changed the images, but suddenly YAMJ doesn't seem to be able to fetch the images

`PosterScanner: getUrlDimensions error: Not a JPEG file: starts with 0xff 0xd9: can't open url: http://thetvdb.com/banners/seasons/72108-5-4.jpg
PosterScanner: Looks like an invalid image, trying a different reader for URL: http://thetvdb.com/banners/seasons/72108-5-4.jpg
PosterScanner: getUrlDimensions error: Not a JPEG file: starts with 0xff 0xd9: can't open url: http://thetvdb.com/banners/seasons/72108-6-3.jpg
PosterScanner: Looks like an invalid image, trying a different reader for URL: http://thetvdb.com/banners/seasons/72108-6-3.jpg
PosterScanner: getUrlDimensions error: I/O error reading PNG header!: can't open url: http://thetvdb.com/banners/seasons/72108-5-4.jpg
PosterScanner: Image[http://thetvdb.com/banners/seasons/72108-5-4.jpg,UNKNOWN] rejected: URL width (0.0) is smaller than poster width (230)
PosterScanner: Using cdon to search for a TvShow poster for NCIS
PosterScanner: getUrlDimensions error: I/O error reading PNG header!: can't open url: http://thetvdb.com/banners/seasons/72108-6-3.jpg
PosterScanner: Image[http://thetvdb.com/banners/seasons/72108-6-3.jpg,UNKNOWN] rejected: URL width (0.0) is smaller than poster width (230)
PosterScanner: Using cdon to search for a TvShow poster for NCIS
`

But if I manually check one of the URLs it says it can't open like [http://thetvdb.com/banners/seasons/72108-5-4.jpg](http://thetvdb.com/banners/seasons/72108-5-4.jpg) it opens fine for me.

**Comment by Omertron** [comment]
See #2796
