### ISSUE TITLE
UNKNOWN flags shown and Certification do not work at all

### ISSUE THREAD

**Issue by ControllingFreak** [YAMJ/yamj-v2#2800]
I used YAMJ r2.10-SNAPSHOT-2016-01-27-2018 for a long time and it was basicall working flawlessly until it started to show UNKNOWN flags randomly for Directors/Plot/etc. Also, there was no generated Certification. 

Updated to r2.10-SNAPSHOT-2017-09-19-1318. Now some titles work, some still get "UNKNOWN", Rating -1 and there is generally no Certification any longer. 

What is happening? Thanks for any feedback. 

I am using JRE 1.6.0_65 on a Max OS X 10.11.6 El Capitan.

**Comment by GabrieleGiuseppini** [comment]
I've also been hitting this quite recently lately. I've found a couple of issues that I'm still investigating:
* One of the IMDB HTML tags for plots has changed and is not being matched by the Imdb plugin anymore;
* Some issues with release dates sometimes cause NullPointerException's that ultimately lead to many movie attributes left as UNKNOWN

I'll post more later.
