### ISSUE TITLE
updates yamj v 2 cannot downloaded 

### ISSUE THREAD

**Issue by chocoprinsje** [YAMJ/yamj-v2#2806]
i can not download the new updates 
i got this error 
The requested URL /sites/default/files/YAMJ/yamj-2.10-SNAPSHOT-2017-06-21-1511-3893a02-bin.zip was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by Omertron** [comment]
http://jenkins.omertron.com/job/YAMJ/ws/distribution/target/
