### ISSUE TITLE
Editable source for image files? Which font(s) used

### ISSUE THREAD

**Issue by SenorSmartyPants** [YAMJ/yamj-v2#2813]
I'm looking for the source files for some of the PNGs in the default skin. Or any skins based on those like 5150 or ÆON Movie Wall.

Specifically the flag style images like https://github.com/YAMJ/yamj-v2/blob/master/distribution/skins/default/resources/hd-720.png
![hd-720](https://user-images.githubusercontent.com/991618/178376996-8cb6b1bd-fb8a-4ad5-bfbe-da8152b20da7.png)

I'd like to add a couple more like this, but want to match the look/font.

This if for more [Jellyfin-nmt](https://github.com/SenorSmartyPants/jellyfin-nmt) project.

Any points to either editable files (like PSDs, or other gimp compatible formats) or even just font names would be great.

**Comment by Omertron** [comment]
I don't think they were generated with anything specific. I would guess they were manually created or "borrowed" from somewhere else.
Sorry.

**Comment by SenorSmartyPants** [comment]
I asked on a fonts forum and found out the font family. Univers Condensed was the best match.

Made some more flags. https://github.com/SenorSmartyPants/jellyfin-nmt/commit/a64cd72eb5fe1e38fb0334012fffeaa8a960e1a9
